In [11]:
import pandas as pd
import random
from datetime import datetime, timedelta
from google.colab import files

In [13]:
job_titles = ['Data Analyst', 'Data Analyst ', 'Senior Data Analyst', 'Data Analyst II', 'Junior Data Analyst', 'sr. data analyst', 'DATA ANALYST', 'Data Scientist', 'Business Analyst']
companies = ['TechCorp', 'DataSolutions', 'FinanceHub', 'ArabianTech', 'GulfData', 'Global_Inventions', 'N/A', 'TechCorp', 'InnoTech', 'AlphaData']
locations = ['Riyadh, Saudi Arabia', 'Cairo, Egypt', 'Dubai, UAE', 'Remote', 'Amman, Jordan', 'Casablanca, Morocco', 'Egypt', 'cairo', 'Jeddah', 'Abu Dhabi']
job_types = ['Full-time', 'Part-time', 'Contract', 'Remote', 'Full-time']
skills_list = ['Python, SQL, Power BI', 'Excel, SQL, Tableau', 'Python, R, Machine Learning', 'SQL, Looker, ETL', 'Python, Statistics', 'SQL, SAS, Excel']

raw_data = []
base_date = datetime.today()

for i in range(15000):
    title = random.choice(job_titles) if random.random() > 0.08 else 'N/A'
    company = random.choice(companies) if random.random() > 0.1 else 'N/A'
    location = random.choice(locations) if random.random() > 0.05 else 'N/A'
    j_type = random.choice(job_types)
    skills = random.choice(skills_list)

    days_ago = random.randint(0, 60)
    if random.random() > 0.15:
        date_posted = (base_date - timedelta(days=days_ago)).strftime('%Y-%m-%d')
    else:
        date_posted = f"Released {random.randint(1, 4)} weeks ago"

    raw_data.append({
        "Job_Title": title,
        "Company": company,
        "Location": location,
        "Job_Type": j_type,
        "Date_Posted": date_posted,
        "Skills_Required": skills
    })

df = pd.DataFrame(raw_data)


df_duplicates = df.head(1500)
df = pd.concat([df, df_duplicates], ignore_index=True)

filename = "raw_jobs_data.csv"
df.to_csv(filename, index=False, encoding='utf-8-sig')

print(f"Success: Generated {len(df)} rows.")
display(df.head())
files.download(filename)

Success: Generated 16500 rows.

,Job_Title,Company,Location,Job_Type,Date_Posted,Skills_Required
0,DATA ANALYST,InnoTech,"Amman, Jordan",Part-time,2026-08-03,"Python, SQL, Power BI"
1,Junior Data Analyst,Global_Inventions,"Amman, Jordan",Part-time,2026-07-03,"SQL, Looker, ETL"
2,Senior Data Analyst,TechCorp,Abu Dhabi,Full-time,Released 3 weeks ago,"SQL, Looker, ETL"
3,Data Analyst,ArabianTech,Jeddah,Contract,Released 3 weeks ago,"Python, Statistics"
4,Junior Data Analyst,TechCorp,Jeddah,Part-time,2026-06-24,"Python, SQL, Power BI"

In [14]:
import numpy as np
from datetime import datetime

In [15]:
df.drop_duplicates(inplace=True)

In [16]:
df['Job_Title'] = df['Job_Title'].str.strip().str.title()
df['Company'] = df['Company'].str.strip()
df['Location'] = df['Location'].str.strip()

In [17]:
df.replace('N/A', np.nan, inplace=True)

In [18]:
df.dropna(subset=['Job_Title', 'Company'], inplace=True)

In [22]:
def estimate_salary(row):
  title = str(row['Job_Title']).lower()
  location = str(row['Location']).lower()
  if 'senior' in title or 'sr' in title or 'ii' in title:
      base_salary = random.randint(5000, 8000)
  elif 'junior' in title or 'jr' in title:
      base_salary = random.randint(2000, 3500)
  else:
      base_salary = random.randint(3500, 5500)
  if 'riyadh' in location or 'dubai' in location or 'abu dhabi' in location:
      base_salary *= 1.5
  return int(base_salary)

In [23]:
df['Monthly_Salary_USD'] = df.apply(estimate_salary, axis=1)

In [24]:
def clean_date(date_str):
  date_str = str(date_str)
  if 'weeks ago' in date_str or 'Released' in date_str:
    return (datetime.today() - timedelta(days=14)).strftime('%Y-%m-%d')
  return date_str
df['Date_Posted'] = df['Date_Posted'].apply(clean_date)
df['Date_Posted'] = pd.to_datetime(df['Date_Posted'], errors='coerce')

In [25]:
print(f"Success! Current size: {len(df)} rows.")

Success! Current size: 11110 rows.

In [26]:
display(df.head())

,Job_Title,Company,Location,Job_Type,Date_Posted,Skills_Required,Monthly_Salary_USD
0,Data Analyst,InnoTech,"Amman, Jordan",Part-time,2026-08-03,"Python, SQL, Power BI",5345
1,Junior Data Analyst,Global_Inventions,"Amman, Jordan",Part-time,2026-07-03,"SQL, Looker, ETL",2266
2,Senior Data Analyst,TechCorp,Abu Dhabi,Full-time,2026-07-30,"SQL, Looker, ETL",8203
3,Data Analyst,ArabianTech,Jeddah,Contract,2026-07-30,"Python, Statistics",3709
4,Junior Data Analyst,TechCorp,Jeddah,Part-time,2026-06-24,"Python, SQL, Power BI",2811

In [27]:
df.to_csv("cleaned_jobs_data.csv", index=False, encoding='utf-8-sig')
files.download("cleaned_jobs_data.csv")